from analysis.test.python import TEST_DATA_FOLDER

CURRENT_TEST_DATA_FOLDER = TEST_DATA_FOLDER / 'utils'

DF_UTILS_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'df_utils'

PARALLEL_UTILS_DATA_FOLDER = CURRENT_TEST_DATA_FOLDER / 'parallel_utils'
